syntax on
set number
set bs=indent,eol,start
set nocompatible
set showcmd
set ruler
set mouse=
set showtabline=2
set title
set confirm
set statusline=%<%f%h%m%r%=format=%{&fileformat}\ file=%{&fileencoding}\ enc=%{&encoding}\ %b\ 0x%B\ %l,%c%V\ %P 
set hidden 
set t_Co=256
set smartindent
set autoindent
set tabstop=4
set shiftwidth=4 
set cursorline
set autoread
set pastetoggle=
set splitright 
set splitbelow 
"set foldmethod=syntax 
set completeopt=longest,menuone 
set infercase
set noswapfile
set nobackup
set encoding=utf-8
set termencoding=utf-8
set fileformat=unix
set wildmenu
set wcm=<TAB>
